/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'page-types': PageType;
    users: User;
    tenants: Tenant;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'page-types': PageTypesSelect<false> | PageTypesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'el' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Pages are scoped per tenant. Each page is linked to a tenant-specific page type and stores its editable content as JSON data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Unique per tenant. Used in the page URL. Example: home, about, header-footer-ftiaxesite.
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  /**
   * Page template that defines the editable fields and layout for this tenant.
   */
  pageType: number | PageType;
  /**
   * Optional internal summary describing the purpose of this page.
   */
  summary?: string | null;
  /**
   * Διαχειριστείτε τα περιεχόμενα των ενοτήτων της σελίδας.
   */
  sections?: {
    /**
     * Hero section στην αρχή της σελίδας.
     */
    hero: {
      headline: string;
      /**
       * Υπότιτλος hero με πολλαπλές γραμμές.
       */
      subheadline?: string | null;
      cta?: string | null;
      /**
       * Εικόνα hero.
       */
      image?: (number | null) | Media;
      /**
       * Στατιστικά κάτω από το CTA.
       */
      stats?:
        | {
            value: string;
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Ενότητα λειτουργιών / πλεονεκτημάτων.
     */
    features?: {
      title?: string | null;
      subtitle?: string | null;
      /**
       * Λίστα λειτουργιών.
       */
      items?:
        | {
            icon?: ('clock' | 'euro' | 'trendingUp' | 'shield' | 'smartphone' | 'zap') | null;
            title: string;
            description: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Ενότητα βημάτων διαδικασίας.
     */
    process?: {
      title?: string | null;
      subtitle?: string | null;
      /**
       * Βήματα διαδικασίας.
       */
      steps?:
        | {
            number?: string | null;
            icon?: ('fileText' | 'wand2' | 'checkCircle2') | null;
            title: string;
            description: string;
            color?: ('teal' | 'navy') | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Ενότητα φόρμας επικοινωνίας.
     */
    contact?: {
      title?: string | null;
      subtitle?: string | null;
      form?: {
        name?: string | null;
        email?: string | null;
        phone?: string | null;
        voicePrompt?: string | null;
        voiceListening?: string | null;
        voiceTranscript?: string | null;
        submit?: string | null;
      };
    };
  };
  /**
   * Κοινό header/footer για όλες τις σελίδες του tenant.
   */
  sharedLayout?: {
    /**
     * Ρυθμίσεις κεφαλίδας.
     */
    header?: {
      /**
       * Κείμενο λογοτύπου.
       */
      logo_text?: string | null;
      /**
       * Μενού πλοήγησης.
       */
      menu?:
        | {
            label: string;
            link: string;
            id?: string | null;
          }[]
        | null;
      cta?: {
        label?: string | null;
        link?: string | null;
      };
    };
    /**
     * Ρυθμίσεις υποσέλιδου.
     */
    footer?: {
      brand?: {
        name?: string | null;
        tagline?: string | null;
      };
      contact?: {
        title?: string | null;
        email?: string | null;
        phone?: string | null;
      };
      links?: {
        title?: string | null;
        items?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
      };
      copyright?: string | null;
    };
  };
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Search engine metadata for this page.
   */
  seo?: {
    /**
     * Overrides the default meta title (defaults to page title).
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for URLs and identifying the tenant across the system
   */
  slug: string;
  /**
   * Optional domain used to map requests to this tenant (e.g. www.example.com)
   */
  domain?: string | null;
  /**
   * Primary locale for this tenant
   */
  defaultLocale?: ('el' | 'en') | null;
  /**
   * Optional JSON blob storing tenant specific theme settings (colours, fonts, etc.)
   */
  theme?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Arbitrary tenant level configuration (header/footer references, integrations, etc.)
   */
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Page templates are unique per tenant and define the form schema for associated pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-types".
 */
export interface PageType {
  id: number;
  /**
   * Tenant that owns this page type
   */
  tenant: number | Tenant;
  name: string;
  /**
   * Unique per tenant (e.g. landing-ftiaxesite, about-ftiaxesite).
   */
  slug: string;
  description?: string | null;
  /**
   * JSON schema describing the editable fields for this page type (e.g. sections, blocks, components).
   */
  fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * If true, new pages for this tenant default to this page type.
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  password?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  username?: string | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'page-types';
        value: number | PageType;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: number | PayloadKv;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  status?: T;
  pageType?: T;
  summary?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              cta?: T;
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
        process?:
          | T
          | {
              title?: T;
              subtitle?: T;
              steps?:
                | T
                | {
                    number?: T;
                    icon?: T;
                    title?: T;
                    description?: T;
                    color?: T;
                    id?: T;
                  };
            };
        contact?:
          | T
          | {
              title?: T;
              subtitle?: T;
              form?:
                | T
                | {
                    name?: T;
                    email?: T;
                    phone?: T;
                    voicePrompt?: T;
                    voiceListening?: T;
                    voiceTranscript?: T;
                    submit?: T;
                  };
            };
      };
  sharedLayout?:
    | T
    | {
        header?:
          | T
          | {
              logo_text?: T;
              menu?:
                | T
                | {
                    label?: T;
                    link?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
            };
        footer?:
          | T
          | {
              brand?:
                | T
                | {
                    name?: T;
                    tagline?: T;
                  };
              contact?:
                | T
                | {
                    title?: T;
                    email?: T;
                    phone?: T;
                  };
              links?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          id?: T;
                        };
                  };
              copyright?: T;
            };
      };
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-types_select".
 */
export interface PageTypesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  fields?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  roles?: T;
  username?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  defaultLocale?: T;
  theme?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}